@host=http://localhost:5085

Get {{host}}/authTest
Authorisation: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmMGFmNDU4My05ZDkyLTQ2OWUtOWY0Ny03N2M4M2ZlNjU5MjEiLCJnaXZlbl9uYW1lIjoiRmlyc3ROYW1lIiwiZmFtaWx5X25hbWUiOiJMYXN0TmFtZSIsImp0aSI6ImMyNDc5Y2ZkLWU4YzItNGEyNC04ZWE2LTA5MTJkOTdlZTc1NCIsImV4cCI6MTczNzg2MDA4NCwiaXNzIjoiQXV0aEZyb21TY3JhdGNoIiwiYXVkIjoiQXV0aEZyb21TY3JhdGNoIn0.U7Ttati2Xxg3cpodYAIk0aRYCUPspaldba7-x0yTJ1c